### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by ajiho** [NicolasCARPi/dropzone#1]
Although there are many Vue or React UI libraries that provide file upload components, I believe that traditional MVC development methods cannot do without their own file upload components, because I need to upload files in my jquery project. I searched for many JavaScript plugins related to file upload on GitHub, but almost all of them are no longer maintained. Thank you again

**Comment by NicolasCARPi** [comment]
You're welcome! :)

**Comment by ajiho** [comment]
Do you have any plans recently? I really want to contribute to open source, but I only know some simple things. What can I do if needed?

**Comment by NicolasCARPi** [comment]
What you can do is scour the open issues and PR on the upstream repo, and bring them here if you think they are relevant enough. Give a priority to bugfixes, not new features.
