### ISSUE TITLE
Is Dropzone supposed to be an ES6 module?

### ISSUE THREAD

**Issue by MagnusOxlund** [NicolasCARPi/dropzone#17]
The [installation chapter](https://docs.dropzone.dev/getting-started/installation/npm-or-yarn#javascript) of the official documentation from the original repo seems to indiciate Dropzone is an ES6 module, but at the same time it also recommends loading the module using non-ES6 module solutions:

> This standard is called [ECMAScript modules](https://nodejs.org/api/esm.html), also commonly referred to as [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). This has caused JavaScript modules to become a defacto standard, which is why I recommend to use this approach.

> In order for Dropzone to find the #my-form the element must already exist. Either put your <script> import at the end of your HTML file, or use some sort of window.onload logic.

Importing the latest Dropzone distribution (version 7.1.5 of this repo via [unpkg](https://unpkg.com/@deltablot/dropzone@7.1.5/dist/dropzone-min.js)) as a standalone ES6 module doesn't work, and it doesn't look like it's exported as one either.

I understand the docs are left over from the original author, but are there any plans to implement the standalone distribution as an ES6 module?

**Comment by NicolasCARPi** [comment]
The installation you should look at is this: https://github.com/NicolasCARPi/dropzone?tab=readme-ov-file#quickstart

I have no control over the docs, but they tell the same thing: yes it can be imported as an ES6 module, it has been the case for a very long time.

> doesn't work, and it doesn't look like it's exported as one either.

What do you mean?? I've been using it for **years** as an ES6 module, and of course it's exported: https://github.com/NicolasCARPi/dropzone/blob/45c1adaff8e431d146a2e823431845caf261a11b/package.json#L22-L24 !!

**Comment by MagnusOxlund** [comment]
The keyword here is standalone, i.e., vanilla Javascript. You're quoting the Node `package.json` file. Sorry if I didn't make that clear enough.

**Comment by NicolasCARPi** [comment]
Well, the class is exported: https://github.com/NicolasCARPi/dropzone/blob/45c1adaff8e431d146a2e823431845caf261a11b/src/dropzone.js#L4

I'm really not sure what is your issue or what you're trying to achieve, but there is nothing special about it. It's a library, it exports a class, you can use it in your code.

**Comment by MagnusOxlund** [comment]
The class is exported in the source, but it's not available in the distributed file at [unpkg.com](https://unpkg.com/@deltablot/dropzone@7/dist/dropzone-min.js.). I'm just going off the example in the readme, but you're welcome to correct me if I'm using it wrong.

What I'm trying to do is import Dropzone as an ES6 module, using a standard ES6 import statement from within another ES6 module to avoid things like placing Dropzone in the global namespace or listening for DOMContentLoaded.

Here's an example:
``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="module" src="https://unpkg.com/@deltablot/dropzone@7/dist/dropzone-min.js"></script>
    <script type="module" src="/test.js"></script>
</head>
<body>
    <div id="elementId"></div>
</body>
</html>
```

``` js
// test.js
import { Dropzone } from "https://unpkg.com/@deltablot/dropzone@7/dist/dropzone-min.js";
const dropzone = new Dropzone("#elementId", { url: "/file/post" });
// SyntaxError: Importing binding name 'Dropzone' is not found.
```

**Comment by NicolasCARPi** [comment]
I see, maybe you can try with:

~~~javascript
import { Dropzone } from "https://unpkg.com/@deltablot/dropzone@7/dist/dropzone.mjs";
// or
import { Dropzone } from "https://unpkg.com/@deltablot/dropzone@7/dist/dropzone.js";
~~~

(see `dist` folder https://www.npmjs.com/package/@deltablot/dropzone?activeTab=code)

Here you're basically mixing a package manager style (npm/yarn) import with a traditional script import, and I think that's why it doesn't work. Using the `.mjs` might work better. Are you not using npm/yarn in your project??

**Comment by MagnusOxlund** [comment]
Excellent, using `dropzone.mjs` did the trick. I hadn't noticed the file earlier, so thanks for pointing it out.

> Are you not using npm/yarn in your project??

No, the backend for the project I'm working on doesn't use Node, so I don't want to include it as long as I don't need to.

Thank you for the help!
