### ISSUE TITLE
ios on network cell data

### ISSUE THREAD

**Issue by umageddon** [NicolasCARPi/dropzone#23]
Not sure if anyone else is having the same issue, but on iOS 18.1 (mabye other iOS as well?), I  keep getting 'Responded with 0 code' and timeouts with some uploaded images, but only when on cellular data.  When connected to wifi, the issue mostly goes away.

I did some poking around with the receiving PHP script and error log and found that many of the bad files being sent had a blank $_FILES['file']['tmp_name']. I never had the error on iOS 17.

These are my settings that seem to give me the least amount of errors:
timeout: 15000,
resizeHeight: 1000,
resizeQuality: 1,
acceptedFiles: "image/*",
autoProcessQueue: true,
disablePreviews: true,
addRemoveLinks: false

turning off multiple and parallel uploads seemed to help alot, the error rate went from every other file to 1 out of about 5 erroring out

**Comment by NicolasCARPi** [comment]
Hello,

I believe the issue you're witnessing is related to your client/server setup rather than this library. As such, I'm closing this issue as there is nothing actionable for us here.

If you can describe precisely a reproducible bug, please feel free to comment on this issue.
