### ISSUE TITLE
How about rebranding this repository?

### ISSUE THREAD

**Issue by w-masahiro-ct** [NicolasCARPi/dropzone#30]
The original Dropzone repository appears at the top when searched on Google.
It can be somewhat challenging to find this fork unless one specifically looks for it.
So, I suggest adopting an alternative name like Droparea or Dndzone and setting up an official website.
I think this change could help attract more maintainers and increase the star count for this fork.
I'm not particularly good at JavaScript, but I'm happy to help if there's anything I can do.

**Comment by NicolasCARPi** [comment]
Hello,

I do not think what you suggest is necessary. Thanks for the suggestion though! :)
