### ISSUE TITLE
Class Methods not accessible via import

### ISSUE THREAD

**Issue by joeworkman** [NicolasCARPi/dropzone#4]
This is not an issue. I just had a problem that I solved that I thought I would share my solution for with others in case they ran in to similar issues. 

I am using esbuild and was importing Dropzone as usual...

```js
import Dropzone from "@deltablot/dropzone";
```

However, I could not access any of the class methods such as `Dropzone.createElement()`. I was able to fix this through adding the following after the import statement. 

```js
import Dropzone from "@deltablot/dropzone";
globalThis.Dropzone = Dropzone;
```

There may be better ways to handle this but this got the job done for me.

**Comment by NicolasCARPi** [comment]
That's peculiar. Might be related to your environment. Anyway, thanks for opening this issue, it might help someone.
