### ISSUE TITLE
issue with unpkg

### ISSUE THREAD

**Issue by jasonwilliamsau** [NicolasCARPi/dropzone#6]
following the steps for manual inclusion
`<script src="https://unpkg.com/@deltablot/dropzone@7/dist/dropzone.min.js"></script>`
resolves to 
`https://unpkg.com/@deltablot/dropzone@7.1.2/dist/dropzone.min.js`
which returns
`Cannot find "/dist/dropzone.min.js" in @deltablot/dropzone@7.1.2`

Switching to 
`<script src="https://unpkg.com/@deltablot/dropzone@7/dist/dropzone.js"></script>`
resolves to 
`https://unpkg.com/@deltablot/dropzone@7.1.2/dist/dropzone.js`
which works but when included in a page

    <script src="https://unpkg.com/@deltablot/dropzone@7.1.2/dist/dropzone.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // access Dropzone here
            const dropzone = new Dropzone(".dropzone", {
                parallelUploads: 10,
                uploadMultiple: true,
                maxFilesize: 50000000,
                paramName: 'media',
                acceptedFiles: "image/*,video/*"
            });
        });

    </script>

returns the following errors in the console

```
Uncaught ReferenceError: require is not defined
    at dropzone.js:1:55
Uncaught ReferenceError: Dropzone is not defined
    at HTMLDocument.<anonymous> (12/:525:30)

**Comment by NicolasCARPi** [comment]
Hello,

Yes the README contained wrong links, it's `dropzone-min.js` not `dropzone.min.js`.

This URL works: https://www.unpkg.com/@deltablot/dropzone@7.1.2/dist/dropzone-min.js
